plugins {
    id 'java'
    id 'application'
}

group 'com.algorithm'
version '1.0-SNAPSHOT'

ext {
    javaMainClass = "com.algorithm.merkletree.Main"
}

application {
    mainClassName = javaMainClass
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.4'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}